### ISSUE TITLE
Can't use newCompressedData

### ISSUE THREAD

**Issue by weakman54** [MikuAuahDark/lily#1]
Looking through the source code, it seems you've missed to include a minarg to the call at line 144 of lily_thread.lua (Sorry for not doing a proper pull request or specifying better, in a bit of a rush atm =/ )

**Comment by MikuAuahDark** [comment]
Should be a fuckup when writing Lily. Fixed.

**Comment by weakman54** [comment]
Damn, that was fast, thanks!
