### ISSUE TITLE
NewImage does not handle ImageData as argument

### ISSUE THREAD

**Issue by weakman54** [MikuAuahDark/lily#2]
Calling the loader functions as {"newImage", [imageData]} throws an error, since the newImage function always tries to use newImageData (or newCompressedData) on the given argument. (handler function at line 129)

Argument should probably be checked so that it isn't already ImageData or CompressedData type.

As an aside, the fact that "newImage" tries to make the file into CompressedData or ImageData should probably be documented. (and if a fix for the above is implemented, the order in which it tests what behaviour to use should be specified.)

**Comment by MikuAuahDark** [comment]
I don't see a reason why you want to parallelize `newImage` call if you already have the `ImageData` or `CompressedImageData`. It's just doesn't make sense. Calling `love.graphics.newImage` with `ImageData` as argument is actually pretty fast that parallelization is not needed in that case.

**Comment by weakman54** [comment]
Right, sorry, I think I got a bit overzealous in my testing
