### ISSUE TITLE
Is multi-thread loading useful for loading screens scenarious? 

### ISSUE THREAD

**Issue by ghost** [MikuAuahDark/lily#4]
Since i don't see discussions here, i will use issues instead, sorry.
I'm still new to threads and their best use cases, so: is there any noticeable decrease in loading time for big collection of assets, using multithread solutions, in situations, where i give to user "loading..." screen?
If so, does Lily suits for it?
Or just old:
```
asset1 = love.graphics.newImage("1.png")
asset2 = love.graphics.newImage("2.png")
--etc...
```
Will work better?

**Comment by flamendless** [comment]
Yes, for my game I use lily to load assets and show a loading screen while it's loading

**Comment by MikuAuahDark** [comment]
With this library, other than reducing load time for many assets (by spreading the "load" call to multiple threads) it also won't block the LOVE main thread\*.

\*I've heard reports of it blocking LOVE main thread too with large assets and auto-generated mipmaps.

**Comment by ghost** [comment]
Good, then i will try to use this library then!
Thanks, everyone!
I will close _*issue*_ then
