### ISSUE TITLE
how to `lily.quit()` on `love.errorhandler`?

### ISSUE THREAD

**Issue by gphg** [MikuAuahDark/lily#5]
I managed to get lily quit on `love.quit` callback by following code:
```lua
function love.quit()
	local lily = package['lily'] or package['libs.lily'] or package['path.to.lily'] or nil
	if lily then 
		lily.quit()
	end
end
```

But how to do it on `love.errorhandler`. Without it, an usual error if `lily.quit()` is not called popped out after the error message displayed and program quited.
```
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by gphg** [comment]
I somehow managed to get it right without completely rewrite the errorhandler.
```lua
-- cache the function
local old_errorhandler = love.errorhandler
function love.errorhandler(msg)
	-- quit lily before original errorhandler get called
	local lily = package['lily'] or package['libs.lily'] or package['path.to.lily'] or nil
	if lily then 
		lily.quit()
	end
	-- call original cached errorhandler function
	old_errorhandler(msg)
end
```

**Comment by gphg** [comment]
Above solution doesn't work. On unexpected error, the program simply quits without tell any error. I had to uncomment it.

**Comment by banepwn** [comment]
`love.errorhandler` is supposed to return a function. When detouring it, you need to make sure your function returns the same values as the old one. Do `return old_errorhandler(msg)`.

**Comment by gphg** [comment]
I debug it, and it seems the old errorhandler is nil.
![image](https://github.com/MikuAuahDark/lily/assets/46024870/8c93b2e7-779d-4469-8a3e-4dccb0e9ea6e)

Updated:
I'm on latest stable version. And it is `love.errhand`, not `love.errorhandler`. But the wiki page says otherwise. :/
```lua
-- Something like this:
local old_errorhandler = love.errorhandler or love.errhand
function love.errorhandler(msg)
	lilyQuit() -- a defined function somewhere to call lily.quit
	return old_errorhandler(msg)
end
```

**Comment by banepwn** [comment]
That's because LÖVE's default error handler is actually in `love.errhand`. In the event of an error, LÖVE will check if `love.errorhandler` exists first, and then `love.errhand` if it doesn't, then a third inaccessible function if neither exist.

**Comment by gphg** [comment]
![image](https://github.com/MikuAuahDark/lily/assets/46024870/581cf79d-843d-4d24-ace4-3121542f154c)
https://love2d.org/wiki/love.errhand
![image](https://github.com/MikuAuahDark/lily/assets/46024870/d3fdfc1a-53ef-40ec-9951-ebe50e38ef2b)

Closing this issue.
